unbind r
bind r source-file ~/.tmux.conf

set -g prefix C-s

set -g mouse on

set -g mode-keys vi

# detectar comando de clipboard
if-shell 'command -v pbcopy >/dev/null 2>&1' \
  "set -g @clipboard_cmd 'pbcopy'" \
  "if-shell 'command -v wl-copy >/dev/null 2>&1' \
    \"set -g @clipboard_cmd 'wl-copy'\" \
    \"set -g @clipboard_cmd 'xclip -selection clipboard'\""

# copiar en copy-mode (vi) al clipboard del sistema
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "#{@clipboard_cmd}"

# también con 'y' estilo vim
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "#{@clipboard_cmd}"

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

set-option -g status-position top

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-cpu'

# Other examples:
set -g @plugin 'catppuccin/tmux#v2.1.3' # See https://github.com/catppuccin/tmux/tags for additional tags
set -g @catppuccin_flavor 'macchiato' # latte, frappe, macchiato or mocha
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"
set -g @catppuccin_status_background "#25273a"
set -g @catppuccin_directory_text "#{pane_current_path}"
# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left "#{E:@catppuccin_status_directory}#[fg=#{@_ctp_status_bg},reverse]#[fg=#{@thm_fg},bg=#{@_ctp_status_bg},noreverse]  "
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_battery}"
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux'
run '~/.tmux/plugins/tpm/tpm'
